#!/bin/sh


echo "In pre-commit-hook"
test_fmt() {

    echo "checking if all go files are formatted"
    hash gofmt 2>&- || { echo >&2 "gofmt not in PATH."; exit 1; }


	# use gofmt to scan whole repo for unformatted go files
	lines_of_unformatted_code=$(gofmt -l . )
	if [ "$lines_of_unformatted_code" ]; then
        echo "NOTOK: There are go files not formatted"
		echo $lines_of_unformatted_code
		exit 1;
    else
		echo "OK: All go files formatted"
    fi
}

case "$1" in
    --about )
        echo "Check Go code formatting"
        ;;
    * )
        test_fmt
        ;;
esac